### ISSUE TITLE
gh-pages에 배포 시 발생하는 에러

### ISSUE THREAD

**Issue by akswnd98** [GiveUsMoney/FanFixiv-user-page#22]
**버그에 대한 설명**
1. develop branch에서 pnpm build:gh가 에러를 내보냅니다.
2. font가 안 불러와 집니다.
3. Router가 동작하지 않습니다.

**재현방법**
1. repository directory에서 git checkout develop후 pnpm build:gh를 입력합니다.
2. build된 index.css를 열어봅니다.

**예상되는 원인**
- package.json의 build:gh 커멘드가 craco build가 아닌 react-scripts build로 되어있습니다.
- '@mui/system/styled'를 import 합니다.
- font/index.css에서 %PUBLIC_URL%을 생략하고 font를 불러옵니다.
- BaseRouter에서 baesname이 지정되지 않았습니다.

**Comment by Roharui** [comment]
제가 겪었던 버그는 `npm start`이후 발생했어요. 

**에러 메세지**
```
Module not found: Error: Can't resolve '@mui/system/styled' in 'D:\Privrate\GiveUsMoney\FanFixiv\frontend\FanFixiv-user-page\src\components\Navigation\Search'
```

**Comment by Roharui** [comment]
[`github page`](https://giveusmoney.github.io/FanFixiv-user-page/)가 정상적으로 표시되지 않습니다. `npm run build:gh`이후 `npm run deploy:gh`를 하셨나요?

**Comment by Roharui** [comment]
아무래도 `window`환경이랑 `linux`환경의 `builid:gh` 명령구문이 다른것 같습니다. 

환경변수를 지정하기 위해 `window`는 `set` 명령어를 사용하지만 `linux` 환경에서는 `foo=variable` 형식으로 변수를 지정합니다. 
그렇기에 window용 build 명령어와 linux용 build 명령어를 따로 선언해두어야 할것 같습니다.

**Comment by Roharui** [comment]
그리고 gh-page 배포후 다음 문제가 발생합니다.

**Router BasePath 지정 문제**
- react Router가 BasePath를 인식해서 404에러가 발생하는 문제가 있습니다. 이 부분은 [여기](https://medium.com/@_diana_lee/react-react-router-%EC%A0%81%EC%9A%A9%ED%95%9C-react-%EC%95%B1%EC%9D%84-github-pages%EB%A1%9C-%EB%B0%B0%ED%8F%AC%ED%95%98%EB%8A%94-%EB%B2%95-5f6119c6a5d9)에 해결책이 존재합니다.

**index.css Font 경로 지정 문제**
- index.css에 있는 font path로 불러오는 경로가 gh-page에서 배포된 경로와 일치하지 않는 문제점이 발생하였습니다. 이 부분은 index.css의 font path를 배포시 변형하는 해결 방법이 있습니다.
