### ISSUE TITLE
MUI 설치 및 CSS in JS 관련 이슈

### ISSUE THREAD

**Issue by akswnd98** [GiveUsMoney/FanFixiv-user-page#6]
**프로세스**

- [x] css in js 결정 (emotion vs ~~styled-components~~)
- [x] mui 설치
- [x] mui theme 정의
  - palette
  - font

**Comment by dalcon10028** [comment]
이번 작업 공용으로 사용하는 거 세팅할 게 몇 개 더 있어서 가능하시면 이 이슈에서 한번에 부탁드릴게요.

 - [x] mui 설치
 - [x] theme 정의
   - palette
   - font
- [ ] ~~[svg icon wrapper component](https://react-svgr.com/docs/getting-started) 설치~~

reference
https://mui.com/material-ui/customization/theming/
https://react-svgr.com/docs/getting-started

**Comment by akswnd98** [comment]
https://velog.io/@juno7803/React-React%EC%97%90%EC%84%9C-SVG-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0

webpack으로 svg file 자동 로딩을 하려면 webpack preset이 먼저 필요할 거 같아서 (eject or craco 이슈) 다른 이슈로 분리해서 진행하는게 나을거 같습니다.

**Comment by dalcon10028** [comment]
네 확인해주셔서 감사합니다

**Comment by dalcon10028** [comment]
이거 제가 가져갈게여 리뷰 부탁드립니다
