### ISSUE TITLE
svgr 적용

### ISSUE THREAD

**Issue by akswnd98** [GiveUsMoney/FanFixiv-user-page#9]
>.svg 파일을 리엑트 컴포넌트로 읽을 수 있게 해주는 라이브러리 입니다
https://www.npmjs.com/package/@svgr/webpack

**할 일**

- [x] svgr 설치
- [x] webpack 설정

**Comment by Roharui** [comment]
이것도 설명 추가 부탁드립니다

**Comment by Roharui** [comment]
-
